apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: default
type: Opaque
data:
  KEYCLOAK_ADMIN: $(echo -n "caosordenado" | base64)
  KEYCLOAK_ADMIN_PASSWORD: $(echo -n "***REMOVED***" | base64)
  POSTGRES_USER: $(echo -n "keycloak" | base64)
  POSTGRES_PASSWORD: $(echo -n "POy3R.n41b4F" | base64)
  POSTGRES_DB: $(echo -n "keycloak-db" | base64)
