apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: portainer
spec:
  entryPoints: [ web ]
  routes:
    - match: Host(`portainer.home.server`)
      kind: Rule
      services:
        - name: portainer
          namespace: portainer
          port: 9000
