apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-crawler-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/crawler`)
      kind: Rule
      middlewares:
        - name: crawler-stripprefix
      services:
        - name: web-crawler
          namespace: default
          port: 8000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crawler-stripprefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /crawler 