apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config-static
  namespace: observability
data:
  promtail.yaml: |
    server:
      http_listen_port: 3101
      log_level: debug

    clients:
      - url: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push

    positions:
      filename: /run/promtail/positions.yaml

    scrape_configs:
      - job_name: static-containers
        static_configs:
          - targets:
              - localhost
            labels:
              job: static-containers
              __path__: /var/log/containers/*ollama*.log
          - targets:
              - localhost  
            labels:
              job: static-containers
              __path__: /var/log/containers/*renderer*.log
          - targets:
              - localhost
            labels:
              job: static-containers  
              __path__: /var/log/containers/*web-crawler*.log
          - targets:
              - localhost
            labels:
              job: static-containers  
              __path__: /var/log/containers/*traefik*.log
