apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: observability
type: Opaque
stringData:
  # Credenciales de admin de Grafana
  GF_SECURITY_ADMIN_USER: "__GRAFANA_ADMIN_USER__"
  GF_SECURITY_ADMIN_PASSWORD: "__GRAFANA_ADMIN_PASSWORD__"

  #_OPTIONAL_# Clave para firmar sesiones/csrf (si no la sete√°s, Grafana genera una)
  #_OPTIONAL_# GF_SECURITY_SECRET_KEY: "__GRAFANA_SECRET_KEY__"
