apiVersion: v1
kind: Secret
metadata:
  name: langflow-secret
  namespace: default
type: Opaque
stringData:
  LANGFLOW_AUTO_LOGIN: "__LANGFLOW_AUTO_LOGIN__"
  LANGFLOW_SUPERUSER: "__LANGFLOW_SUPERUSER__"
  LANGFLOW_SUPERUSER_PASSWORD: "__LANGFLOW_SUPERUSER_PASSWORD__"
  #_OPTIONAL_# Add more Langflow secrets as needed 