apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: shared
type: Opaque
stringData:
  POSTGRES_USER: __POSTGRES_USER__
  POSTGRES_PASSWORD: __POSTGRES_PASSWORD__
  POSTGRES_DB: __POSTGRES_DB__
  #_OPTIONAL_# Additional databases can be created using this format:
  #_OPTIONAL_# POSTGRES_MULTIPLE_DATABASES: __POSTGRES_MULTIPLE_DATABASES__ 