apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: shared
type: Opaque
stringData:
  # Replace __REDIS_PASSWORD__ with a strong password
  redis-password: "__REDIS_PASSWORD__"
  
  # Optional additional configurations
  #_OPTIONAL_ redis-user: "__REDIS_USER__"
  #_OPTIONAL_ redis-config: |
  #   maxmemory 2gb
  #   maxmemory-policy allkeys-lru 