apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ollama
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/ollama`)
      middlewares:
        - name: ollama-stripprefix
          namespace: default
      services:
        - name: ollama
          port: 11434 