apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - datasource-loki.configmap.yaml
  - datasource-prometheus.configmap.yaml
  - dashboards-provider.configmap.yaml
  - dashboard-k8s-logs.configmap.yaml
  - dashboard-k8s-metrics.configmap.yaml