apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - rbac.yaml
  - configmaps.yaml
  - services.yaml
  - deployments.yaml
  - secrets.yaml
  - storage.yaml
  - redis-secret.yaml
  - crds.yaml
  - ingress.yaml
  - middleware.yaml

commonLabels:
  app.kubernetes.io/part-of: argocd 