apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-gc

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-gc
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-gc
subjects:
  - kind: ServiceAccount
    name: pod-gc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-gc
