apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.io
spec:
  group: traefik.io
  names:
    kind: IngressRoute
    listKind: IngressRouteList
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                entryPoints:
                  type: array
                  items:
                    type: string
                routes:
                  type: array
                  items:
                    type: object
                    properties:
                      match:
                        type: string
                      kind:
                        type: string
                      middlewares:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            namespace:
                              type: string
                      services:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            port:
                              type: integer
                            kind:
                              type: string
                            scheme:
                              type: string
                            healthCheck:
                              type: object
                              properties:
                                path:
                                  type: string
                                port:
                                  type: integer
                                interval:
                                  type: string
                                timeout:
                                  type: string
                                followRedirects:
                                  type: boolean
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: middlewares.traefik.io
spec:
  group: traefik.io
  names:
    kind: Middleware
    listKind: MiddlewareList
    plural: middlewares
    singular: middleware
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                stripPrefix:
                  type: object
                  properties:
                    prefixes:
                      type: array
                      items:
                        type: string
                addPrefix:
                  type: object
                  properties:
                    prefix:
                      type: string
                headers:
                  type: object
                  properties:
                    customRequestHeaders:
                      type: object
                      additionalProperties:
                        type: string
                    customResponseHeaders:
                      type: object
                      additionalProperties:
                        type: string
                    accessControlAllowCredentials:
                      type: boolean
                    accessControlAllowHeaders:
                      type: array
                      items:
                        type: string
                    accessControlAllowMethods:
                      type: array
                      items:
                        type: string
                    accessControlAllowOriginList:
                      type: array
                      items:
                        type: string
                    accessControlExposeHeaders:
                      type: array
                      items:
                        type: string
                    accessControlMaxAge:
                      type: integer
                redirectScheme:
                  type: object
                  properties:
                    scheme:
                      type: string
                    permanent:
                      type: boolean
                redirectRegex:
                  type: object
                  properties:
                    regex:
                      type: string
                    replacement:
                      type: string
                    permanent:
                      type: boolean
                replacePath:
                  type: object
                  properties:
                    path:
                      type: string
                replacePathRegex:
                  type: object
                  properties:
                    regex:
                      type: string
                    replacement:
                      type: string
                ipWhiteList:
                  type: object
                  properties:
                    sourceRange:
                      type: array
                      items:
                        type: string
                ipBlockList:
                  type: object
                  properties:
                    sourceRange:
                      type: array
                      items:
                        type: string
                rateLimit:
                  type: object
                  properties:
                    average:
                      type: integer
                    burst:
                      type: integer
                compress:
                  type: object
                  properties: {}
                contentType:
                  type: object
                  properties:
                    autoDetect:
                      type: boolean
                digestAuth:
                  type: object
                  properties:
                    users:
                      type: array
                      items:
                        type: string
                forwardAuth:
                  type: object
                  properties:
                    address:
                      type: string
                    authResponseHeaders:
                      type: array
                      items:
                        type: string
                    authRequestHeaders:
                      type: array
                      items:
                        type: string
                    tls:
                      type: object
                      properties:
                        caSecret:
                          type: string
                        caOptional:
                          type: boolean
                        certSecret:
                          type: string
                        keySecret:
                          type: string
                        insecureSkipVerify:
                          type: boolean
                plugin:
                  type: object
                  properties:
                    name:
                      type: string
                    config:
                      type: object
                      additionalProperties: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: traefikservices.traefik.io
spec:
  group: traefik.io
  names:
    kind: TraefikService
    listKind: TraefikServiceList
    plural: traefikservices
    singular: traefikservice
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                weighted:
                  type: object
                  properties:
                    services:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          port:
                            type: integer
                          weight:
                            type: integer
                mirroring:
                  type: object
                  properties:
                    name:
                      type: string
                    port:
                      type: integer
                    mirrors:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          port:
                            type: integer
                          percent:
                            type: integer
                loadBalancer:
                  type: object
                  properties:
                    servers:
                      type: array
                      items:
                        type: object
                        properties:
                          url:
                            type: string
                          weight:
                            type: integer
                    passHostHeader:
                      type: boolean
                    responseForwarding:
                      type: object
                      properties:
                        flushInterval:
                          type: string
                    serversTransport:
                      type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serverstransports.traefik.io
spec:
  group: traefik.io
  names:
    kind: ServersTransport
    listKind: ServersTransportList
    plural: serverstransports
    singular: serverstransport
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serverName:
                  type: string
                insecureSkipVerify:
                  type: boolean
                rootCAsSecrets:
                  type: array
                  items:
                    type: string
                maxIdleConnsPerHost:
                  type: integer
                forwardingTimeouts:
                  type: object
                  properties:
                    dialTimeout:
                      type: string
                    responseHeaderTimeout:
                      type: string
                    idleConnTimeout:
                      type: string
                    readIdleTimeout:
                      type: string
                    pingTimeout:
                      type: string
                certificates:
                  type: array
                  items:
                    type: object
                    properties:
                      certSecret:
                        type: string
                      keySecret:
                        type: string
                disableHTTP2:
                  type: boolean
                peerCertURI:
                  type: string 