apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9080
      targetPort: web
      name: web
    - protocol: TCP
      port: 8080
      targetPort: traefik
      name: traefik
    - protocol: TCP
      port: 5432
      targetPort: postgres
      name: postgres
    - protocol: TCP
      port: 6379
      targetPort: redis
      name: redis
  selector:
    app.kubernetes.io/name: traefik
