apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: langflow
  namespace: default
spec:
  entryPoints:
    - langflow
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: langflow
          port: 7860